#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#  DEPLOY — Portfolio + Sites de Exemplo
#  Instruções para hospedagem gratuita
# ═══════════════════════════════════════════════════════════════════

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║     🚀 DEPLOY — Portfolio + Sites de Exemplo       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "📂 Pasta para deploy: $ROOT_DIR"
echo ""
echo "════════════════════════════════════════════════════════"
echo "📦 MÉTODO RECOMENDADO: Netlify Drop"
echo "════════════════════════════════════════════════════════"
echo ""
echo "1. Acesse: https://app.netlify.com/drop"
echo "2. Arraste a pasta abaixo para o navegador:"
echo "   📁 $ROOT_DIR"
echo ""
echo "Pronto! URL gerada automaticamente:"
echo "   📱 https://NOME-ALEATORIO.netlify.app/portfolio/"
echo ""
echo "════════════════════════════════════════════════════════"
echo "🐙 GitHub Pages"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Crie um repo e execute:"
echo ""
echo "  cd '$ROOT_DIR'"
echo "  git init && git add . && git commit -m 'Portfolio'"
echo "  git branch -M main"
echo "  git remote add origin https://github.com/USER/REPO.git"
echo "  git push -u origin main"
echo ""
echo "Depois ative Pages em Settings > Pages do repositório."
echo ""
echo "════════════════════════════════════════════════════════"
echo "▲ Vercel (se tiver Node.js e conta Vercel)"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  npm i -g vercel && vercel login && vercel --prod"
echo "  cd '$ROOT_DIR' && vercel --prod"
echo ""
echo "════════════════════════════════════════════════════════"
echo "📱 URLs após deploy:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "  Portfolio:   /portfolio/index.html"
echo "  Pizza Prime: /samples/pizza-prime/index.html"
echo "  Barber King: /samples/barber-king/index.html"
echo "  Lumière:     /samples/clinica-lumiere/index.html"
echo "  VitaPet:     /samples/vitapet-veterinaria/index.html"
echo "  Fitness Pro: /samples/fitness-pro/index.html"
echo ""
echo "════════════════════════════════════════════════════════"
echo "⚡ PÓS-DEPLOY: Atualize os links no config.js"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Edite o arquivo: portfolio/js/config.js"
echo "Na seção 'projects', troque o 'link' de cada projeto"
echo "para o URL público real. Exemplo:"
echo ""
echo "  link: 'https://SEU-SITE.netlify.app/samples/pizza-prime/index.html',"
echo ""
